language: php

php:
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

install: composer install

script: phpunit --colors tests

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
