language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script: phpunit --colors tests

matrix:
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
